re_data_postgres:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('DBT_SNOWFLAKE_ACCOUNT_DEV') }}" 
      user: "{{ env_var('DBT_SNOWFLAKE_USER_DEV') }}" 
      password: "{{ env_var('DBT_SNOWFLAKE_PASSWORD_DEV') }}" 
      database: REDATA_TESTING
      warehouse: COMPUTE_WH
      schema: dq
      threads: 4