name: github pages

on: [push, pull_request]

env:
  DBT_PROFILES_DIR: ./integration_tests

jobs:
  run-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    steps:        
      - name: Check out
        uses: actions/checkout@v2

      - uses: actions/setup-python@v1
        with:
          python-version: "3.7.x"

      - name: Install dependencies and run
        working-directory: ./integration_tests
        run: |
          pip install -r requirements.txt
          dbt deps
          dbt run

      - name: Test Postgres
        run: pytest test_dbs.py -k 'test_postgres'

      - name: Test Snowflake
        run: pytest test_dbs.py -k 'test_snowflake'
        if: github.event_name != 'pull_request'
      
      - name: Test BigQuery
        run: pytest test_dbs.py -k 'test_bigquery'
        if: github.event_name != 'pull_request'
      
      - name: Test Redshift
        run: pytest test_dbs.py -k 'test_redshift'
        if: github.event_name != 'pull_request'
